### ISSUE TITLE
 fireice-uk/xmr-stak or xmr-stak/xmr-satk?

### ISSUE THREAD

**Issue by photis** [xmr-stak/xmr-stak#6]
Looking into xmr-stak for Ubuntu 16.04/CUDA 9 now. Should I use this repository or fireice-uk/xmr-stak?

**Comment by psychocrypt** [comment]
The correct reposetory is https://github.com/fireice-uk/xmr-stak
I will remove all branches. This repo was only usefull during the refactoring
